// Catálogo de colonias de la alcaldía Coyoacán.
// Fuente: SEPOMEX (Correos de México) — CPdescarga.txt — sincronizado desde control (2026-06-14)
// Total: 116 asentamientos únicos

export const COLONIAS_COYOACAN = [
  "Adolfo Ruiz Cortínes",
  "Ajusco",
  "Alianza Popular Revolucionaria",
  "Atlántida",
  "Avante",
  "Barrio del Niño Jesús",
  "Barrio La Concepción",
  "Barrio Oxtopulco Universidad",
  "Barrio San Lucas",
  "Barrio Santa Catarina",
  "Bosques de Tetlameya",
  "Cafetales",
  "Campestre Churubusco",
  "Campestre Coyoacán",
  "Cantil del Pedregal",
  "Carmen Serdán",
  "Churubusco Country Club",
  "Ciudad Jardín",
  "Copilco",
  "Copilco El Alto",
  "Copilco El Bajo",
  "Copilco Universidad",
  "Copilco Universidad ISSSTE",
  "Cuadrante de San Francisco",
  "Culhuacán CTM Canal Nacional",
  "Culhuacán CTM CROC",
  "Culhuacán CTM Sección I",
  "Culhuacán CTM Sección II",
  "Culhuacán CTM Sección III",
  "Culhuacán CTM Sección IX-A",
  "Culhuacán CTM Sección IX-B",
  "Culhuacán CTM Sección Piloto",
  "Culhuacán CTM Sección V",
  "Culhuacán CTM Sección VI",
  "Culhuacán CTM Sección VII",
  "Culhuacán CTM Sección VIII",
  "Culhuacán CTM Sección X",
  "Culhuacán CTM Sección X-A",
  "Del Carmen",
  "Educación",
  "El Caracol",
  "El Centinela",
  "El Mirador",
  "El Parque de Coyoacán",
  "El Reloj",
  "El Rosario",
  "El Rosedal",
  "Emiliano Zapata",
  "Emiliano Zapata Fraccionamiento Popular",
  "Empleados Federales",
  "Ermita Churubusco",
  "Espartaco",
  "Ex-Ejido de San Francisco Culhuacán",
  "Ex-Ejido de San Pablo Tepetlapa",
  "Ex-Ejido de Santa Úrsula Coapa",
  "Ex-Hacienda Coapa",
  "Fortín de Chimalistac",
  "Haciendas de Coyoacán",
  "Hermosillo",
  "Huayamilpas",
  "Insurgentes Cuicuilco",
  "Integración Latinoamericana",
  "Jardines de Coyoacán",
  "Jardines del Pedregal de San Ángel",
  "Joyas del Pedregal",
  "La Otra Banda",
  "La Virgen",
  "Las Campanas",
  "Los Cedros",
  "Los Cipreses",
  "Los Girasoles",
  "Los Olivos",
  "Los Sauces",
  "Modulo Social Imán",
  "Nueva Díaz Ordaz",
  "Olímpica",
  "Parque San Andrés",
  "Paseos de Taxqueña",
  "Pedregal de Carrasco",
  "Pedregal de Coyoacán",
  "Pedregal de La Zorra",
  "Pedregal de San Francisco",
  "Pedregal de Santa Úrsula",
  "Pedregal de Santo Domingo",
  "Pedregal del Sur",
  "Petrolera Taxqueña",
  "Prado Churubusco",
  "Prados de Coyoacán",
  "Presidentes Ejidales 1a Sección",
  "Presidentes Ejidales 2a Sección",
  "Pueblo de los Reyes",
  "Pueblo de San Pablo Tepetlapa",
  "Pueblo de Santa Úrsula Coapa",
  "Pueblo La Candelaria",
  "Residencial la Cantera",
  "Romero de Terreros",
  "San Diego Churubusco",
  "San Francisco Culhuacán Barrio de La Magdalena",
  "San Francisco Culhuacán Barrio de San Francisco",
  "San Francisco Culhuacán Barrio de San Juan",
  "San Francisco Culhuacán Barrio de Santa Ana",
  "San Mateo",
  "Santa Cecilia",
  "Santa Martha del Sur Quetzalcoatl",
  "Sector Marina",
  "STUNAM Culhuacan",
  "Tlalpan FOVISSSTE",
  "Torres de Chimalistac",
  "Universidad Nacional Autónoma de México",
  "Viejo Ejido de Santa Úrsula Coapa",
  "Villa Coyoacán",
  "Villa de San Francisco",
  "Villa Quietud",
  "Villas Copilco",
  "Vistas del Maurel",
  "Xotepingo",
] as const;

export type ColoniaCoyoacan = (typeof COLONIAS_COYOACAN)[number];

/** Centro aproximado de Coyoacán, CDMX */
export const COYOACAN_CENTER = {
  latitude: 19.3467,
  longitude: -99.1617,
  zoom: 12.2,
} as const;
